### ISSUE TITLE
Error: 'str' object has no attribute 'starts_with' while importing to Pinecone serverless

### ISSUE THREAD

**Issue by flashblaze** [AI-Northstar-Tech/vector-io#55]
Hi, I exported data from pod based index and replaced a key and value in `VDF_META.json` so I can import it to a specific index in my serverless index:

Before

```
    "indexes": {
        "namespace1": [
            {
                "namespace": "dev-clsix3wzg00052eeep6bdgvcl",
                "index_name": "namespace1",
                "total_vector_count": 84,
                "exported_vector_count": 84,
                "dimensions": 1536,
                "model_name": "text-embedding-ada-002",
                "vector_columns": [
                    "vector"
                ],
                "data_path": "namespace1_dev-clsix3wzg00052eeep6bdgvcl/i1.parquet",
                "metric": "Cosine"
            }
        ]
    },
```

After

```
    "indexes": {
        "namespace1-serverless": [
            {
                "namespace": "dev-clsix3wzg00052eeep6bdgvcl",
                "index_name": "namespace1-serverless",
                "total_vector_count": 84,
                "exported_vector_count": 84,
                "dimensions": 1536,
                "model_name": "text-embedding-ada-002",
                "vector_columns": [
                    "vector"
                ],
                "data_path": "namespace1_dev-clsix3wzg00052eeep6bdgvcl/i1.parquet",
                "metric": "Cosine"
            }
        ]
    },
```

After trying to import via running `import_vdf pinecone --serverless`, I ran into this error:

```
Error: 'str' object has no attribute 'starts_with'
Traceback (most recent call last):
  File "/home/neeraj/.local/lib/python3.10/site-packages/vdf_io/import_vdf_cli.py", line 52, in main
    run_import(span)
  File "/home/neeraj/.local/lib/python3.10/site-packages/vdf_io/import_vdf_cli.py", line 129, in run_import
    import_obj = slug_to_import_func[args["vector_database"]](args)
  File "/home/neeraj/.local/lib/python3.10/site-packages/vdf_io/import_vdf/pinecone_import.py", line 80, in import_vdb
    pinecone_import.upsert_data()
  File "/home/neeraj/.local/lib/python3.10/site-packages/vdf_io/import_vdf/pinecone_import.py", line 172, in upsert_data
    parquet_files = self.get_parquet_files(final_data_path)
  File "/home/neeraj/.local/lib/python3.10/site-packages/vdf_io/import_vdf/vdf_import_cls.py", line 77, in get_parquet_files
    return get_parquet_files(data_path, self.args)
  File "/home/neeraj/.local/lib/python3.10/site-packages/vdf_io/util.py", line 196, in get_parquet_files
    if args.get("hf_dataset", None) or data_path.starts_with("hf://"):
AttributeError: 'str' object has no attribute 'starts_with'. Did you mean: 'startswith'?
```

**Comment by flashblaze** [comment]
Hi @dhruv-anand-aintech did you get a chance to look at it?

**Comment by dhruv-anand-aintech** [comment]
try vdf==0.1.85 I have just uploaded it to pypi

**Comment by flashblaze** [comment]
Thanks. I tested it, and I ran into this error
```
Loading data from parquet files:   0%|                                                        | 0/1 [00:00<?, ?it/s]Importing namespaces:   0%|                                                                  | 0/38 [00:00<?, ?it/s]Importing indexes:   0%|                                                                      | 0/1 [00:01<?, ?it/s]Error: None
Traceback (most recent call last):
  File "/home/neeraj/.local/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 3791, in get_loc
    return self._engine.get_loc(casted_key)
  File "index.pyx", line 152, in pandas._libs.index.IndexEngine.get_loc
  File "index.pyx", line 181, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 7080, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 7088, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: None

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/neeraj/.local/lib/python3.10/site-packages/vdf_io/import_vdf_cli.py", line 53, in main
    run_import(span)
  File "/home/neeraj/.local/lib/python3.10/site-packages/vdf_io/import_vdf_cli.py", line 131, in run_import
    import_obj = slug_to_import_func[args["vector_database"]](args)
  File "/home/neeraj/.local/lib/python3.10/site-packages/vdf_io/import_vdf/pinecone_import.py", line 80, in import_vdb
    pinecone_import.upsert_data()
  File "/home/neeraj/.local/lib/python3.10/site-packages/vdf_io/import_vdf/pinecone_import.py", line 223, in upsert_data
    {
  File "/home/neeraj/.local/lib/python3.10/site-packages/vdf_io/import_vdf/pinecone_import.py", line 224, in <dictcomp>
    row[self.id_column]: row[vector_column_name].tolist()
  File "/home/neeraj/.local/lib/python3.10/site-packages/pandas/core/series.py", line 1040, in __getitem__
    return self._get_value(key)
  File "/home/neeraj/.local/lib/python3.10/site-packages/pandas/core/series.py", line 1156, in _get_value
    loc = self.index.get_loc(label)
  File "/home/neeraj/.local/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 3798, in get_loc
    raise KeyError(key) from err
KeyError: None
```
